source :rubygems

gem 'foreman', '>= 0.63.0'
gem 'json', '>= 1.7.5', :platforms => [:ruby_18]
gem 'nokogiri', '>= 1.5.9'

gem 'activesupport', '>= 4.0.0'
gem 'i18n'
gem 'em-mongo', '>= 0.4.3'
gem 'bson_ext', '>= 1.9.1'  # For mongo.
gem 'em-websocket', '>= 0.5.0'
gem 'eventmachine', '>= 1.0.1'
gem 'eventmachine_httpserver', '>= 0.2.1'
gem 'em-http-request', '~> 1.0.3'
